### ISSUE TITLE
aws login selection fails in Windows 10

### ISSUE THREAD

**Issue by cmaturi** [techservicesillinois/awscli-login#1]
```
C:\Python36\Scripts>aws login
Password:
Please choose the role you would like to assume:
     Account: 224588347132
         [ 0 ]: ASCourseExplorerTeam
         [ 1 ]: ApplicationServicesAdmins
         [ 2 ]: BoxAdmin
         [ 3 ]: CompassAdmin
         [ 4 ]: KalturaAdmin
     Account: 617683844790
         [ 5 ]: ApplicationServicesAdmins
         [ 6 ]: BoxAdmin
         [ 7 ]: CompassAdmin
         [ 8 ]: KalturaAdmin
Selection: 1
Exception in parent:
  File "C:\Python36\lib\site-packages\awscli_login\__main__.py", line 61, in daemonize
    expires,
  File "C:\Python36\lib\site-packages\daemoniker\_daemonize_windows.py", line 107, in _daemonize
    return _daemonize1(*args, _exit_caller=False, **kwargs)
  File "C:\Python36\lib\site-packages\daemoniker\_daemonize_windows.py", line 430, in _daemonize1
    pickle.dump(worker_argv, f, protocol=-1)

AttributeError("Can't pickle local object 'rename_arg.<locals>._rename_arg'",)
Exception in parent:
  File "C:\Python36\lib\site-packages\awscli_login\__main__.py", line 61, in daemonize
    expires,
  File "C:\Python36\lib\site-packages\daemoniker\_daemonize_windows.py", line 107, in _daemonize
    return _daemonize1(*args, _exit_caller=False, **kwargs)
  File "C:\Python36\lib\site-packages\daemoniker\_daemonize_windows.py", line 430, in _daemonize1
    pickle.dump(worker_argv, f, protocol=-1)

AttributeError("Can't pickle local object 'rename_arg.<locals>._rename_arg'",)
```

**Comment by ddriddle** [comment]
I added some debugging code and found that the `session` variable can not be pickled on Windows:

```
Traceback (most recent call last):
  File "c:\users\david riddle\src\awscli-login\src\awscli_login\__main__.py", line 134, in wrapper
    f(profile, session)
  File "c:\users\david riddle\src\awscli-login\src\awscli_login\__main__.py", line 198, in main
    is_parent = daemonize(profile, session, client, role, expires)
  File "c:\users\david riddle\src\awscli-login\src\awscli_login\__main__.py", line 66, in daemonize
    pickle.dumps(session)
AttributeError: Can't pickle local object 'rename_arg.<locals>._rename_arg'
Can't pickle local object 'rename_arg.<locals>._rename_arg'
```

**Comment by ddriddle** [comment]
Neither can the `client` be pickled!

```
Traceback (most recent call last):
  File "c:\users\david riddle\src\awscli-login\src\awscli_login\__main__.py", line 128, in wrapper
    f(profile, session)
  File "c:\users\david riddle\src\awscli-login\src\awscli_login\__main__.py", line 192, in main
    is_parent = daemonize(profile, session, client, role, expires)
  File "c:\users\david riddle\src\awscli-login\src\awscli_login\__main__.py", line 64, in daemonize
    pickle.dumps(client)
_pickle.PicklingError: Can't pickle <class 'botocore.client.STS'>: attribute lookup STS on botocore.client failed
Can't pickle <class 'botocore.client.STS'>: attribute lookup STS on botocore.client failed
```

**Comment by ddriddle** [comment]
After removing the `session` and `client` variable from the pickling process on fork I still receive errors:

```
C:\Program Files\Python37\lib\runpy.py:125: RuntimeWarning: 'daemoniker._daemonize_windows' found in sys.modules after import of package 'daemoniker', but prior to execution of 'daemoniker._daemonize_windows'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Exception in parent:
  File "c:\users\david riddle\src\awscli-login\src\awscli_login\__main__.py", line 69, in daemonize
    role,
  File "C:\Program Files\Python37\lib\site-packages\daemoniker\_daemonize_windows.py", line 107, in _daemonize
    return _daemonize1(*args, _exit_caller=False, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\daemoniker\_daemonize_windows.py", line 453, in _daemonize1
    'Daemon creation worker exited prematurely.'

RuntimeError('Daemon creation worker exited prematurely.')
Exception in parent:
  File "c:\users\david riddle\src\awscli-login\src\awscli_login\__main__.py", line 69, in daemonize
    role,
  File "C:\Program Files\Python37\lib\site-packages\daemoniker\_daemonize_windows.py", line 107, in _daemonize
    return _daemonize1(*args, _exit_caller=False, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\daemoniker\_daemonize_windows.py", line 453, in _daemonize1
    'Daemon creation worker exited prematurely.'

RuntimeError('Daemon creation worker exited prematurely.')
```

**Comment by dmalia1** [comment]
I did some debugging.  daemoniker._daemonize_windows is failing because its trying to execute 'C:\Users\username\AppData\Local\Programs\Python\Python37-32\Scripts\aws.cmd' as a python script, but the 

> @echo
at the beginning of the file is breaking the python parsing, thus terminating the script.

**Comment by edthedev** [comment]
@dmalia1 Thanks for the pull request. Sorry for the delay in merging. I've pulled this into our sprint board.

**Comment by ddriddle** [comment]
Commit 6ad5416 resolves these error message by disabling refresh on Windows systems. In the near future we will look at fixing the refresh feature on Windows.
