### ISSUE TITLE
doesn't compile with python3.6 on ubuntu 17.10

### ISSUE THREAD

**Issue by rb3896** [techservicesillinois/awscli-login#17]
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    with open(path.join(here, 'README.rst'), encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function
Coverage.py warning: No data was collected. (no-data-collected)
Makefile:36: recipe for target '.report' failed

looks like a function did away with a previously depricated call.

**Comment by ddriddle** [comment]
The problem is that you are trying to build the plugin using Python 2.7. See the following example:
```
$ docker run -it --rm ubuntu:17.10
# apt-get update && apt-get install -y python-pip git
# git clone https://github.com/techservicesillinois/awscli-login.git
# cd awscli-login/
# python setup.py build
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    with open(path.join(here, 'README.rst'), encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function
# python --version
Python 2.7.14
```
I was able to build, install, and run the plugin using python3 in a ubuntu 17.10 container:
```
$ docker run -it --rm ubuntu:17.10
# apt-get update && apt-get install -y python3-pip git libxml2-dev libxslt-dev libz-dev
# git clone https://github.com/techservicesillinois/awscli-login.git
# cd awscli-login
# python3 setup.py build
# python3 setup.py install
#
# aws configure set plugins.login awscli_login
# aws login configure
# aws login
# aws s3 ls
```

**Comment by rb3896** [comment]
Apologies, I was rushing to post that and didn't switch back to python3.   Let me try that again.  I got it compiled again, but receive an error during runtime. 

rick@oxygen:~$ python --version
Python 3.6.6
rick@oxygen:~$ pip list| grep keyring
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
keyring (15.1.0)
keyrings.alt (3.0)
rick@oxygen:~$ aws
Error initializing plugin EntryPoint('Windows (alt)', 'keyrings.alt.Windows', None, Distribution('keyrings.alt', '3.0')).
Traceback (most recent call last):
  File "/home/rick/.local/lib/python3.6/site-packages/keyring/backend.py", line 163, in _load_plugins
    init_func = ep.load()
  File "/home/rick/.local/lib/python3.6/site-packages/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/Windows.py", line 9, in <module>
    from . import file_base
  File "/usr/lib/python3/dist-packages/keyrings/alt/file_base.py", line 13, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
Error initializing plugin EntryPoint('file', 'keyrings.alt.file', None, Distribution('keyrings.alt', '3.0')).
Traceback (most recent call last):
  File "/home/rick/.local/lib/python3.6/site-packages/keyring/backend.py", line 163, in _load_plugins
    init_func = ep.load()
  File "/home/rick/.local/lib/python3.6/site-packages/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/file.py", line 11, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
Error initializing plugin EntryPoint('pyfs', 'keyrings.alt.pyfs', None, Distribution('keyrings.alt', '3.0')).
Traceback (most recent call last):
  File "/home/rick/.local/lib/python3.6/site-packages/keyring/backend.py", line 163, in _load_plugins
    init_func = ep.load()
  File "/home/rick/.local/lib/python3.6/site-packages/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/pyfs.py", line 8, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: the following arguments are required: command
rick@oxygen:~$

**Comment by rb3896** [comment]
https://bugs.launchpad.net/usd-importer/+bug/1794041  I think comment #6 has put me on the right track to figuring this out.

**Comment by rb3896** [comment]
confirmed downgrading keyring to 13.2.1 works.   keyring.util.escape was deprecated, and apparently is now removed.

**Comment by ddriddle** [comment]
What operating system are you using? Windows or Ubuntu? Can also please give me the full output of the following command so that I can attempt to reproduce your problem:
```
$ python3 --version
$ pip3 freeze
```
May I also ask why you are building the package instead of using pypi to install the plugin?

**Comment by rb3896** [comment]
pip for me didn't originally find awscli-login, but that's because I wasn't using pip3.   I just installed it again (via pip3) rather than building it again, which upgraded keyring to 16.0.1. and it works again. 

So..   I'm all good.   Perhaps this thread will help someone else, or we can delete it, but for posterity's sake:

rick@oxygen:~$ python --version
Python 3.6.6
rick@oxygen:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
rick@oxygen:~$ pip3 freeze
alabaster==0.7.8
alembic==0.9.3.dev0
apparmor==2.12
apt-xapian-index==0.47
apturl==0.5.2
asn1crypto==0.24.0
aws-shell==0.2.0
awscli==1.16.50
awscli-login==0.1.0a5
Babel==2.4.0
boto3==1.9.40
botocore==1.12.40
certifi==2018.10.15
cffi==1.11.5
chardet==3.0.4
colorama==0.3.9
command-not-found==0.3
configobj==5.0.6
coverage==4.5
cryptography==2.3.1
cupshelpers==1.0
cycler==0.10.0
daemoniker==0.2.3
defer==1.0.6
distro-info==0.18
docutils==0.14
entrypoints==0.2.3
evdev==0.7.0
flake8==3.5.0
httplib2==0.9.2
idna==2.7
imagesize==0.7.1
iotop==0.6
jeepney==0.4
Jinja2==2.10
jmespath==0.9.3
keyring==16.0.1
keyrings.alt==3.0
language-selector==0.1
LibAppArmor==2.12
lxml==4.2.5
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.1.1
mccabe==0.6.1
mypy==0.560
numpy==1.13.3
olefile==0.45.1
openshot-qt==2.4.1
pexpect==4.2.1
Pillow==5.1.0
prompt-toolkit==1.0.15
psutil==5.4.8
pyasn1==0.4.4
pycairo==1.16.2
pycodestyle==2.3.1
pycparser==2.19
pycrypto==2.6.1
pycups==1.9.73
pycurl==7.43.0.1
pyflakes==1.6.0
pyfs==0.0.8
Pygments==2.2.0
pygobject==3.26.1
pyparsing==2.2.0
python-apt==1.6.2
python-dateutil==2.7.5
python-debian==0.1.32
pytz==2018.3
pyudev==0.21.0
pyxdg==0.25
PyYAML==3.13
pyzmq==16.0.2
reportlab==3.4.0
requests==2.20.0
requests-unixsocket==0.1.5
roman==2.0.0
rsa==3.4.2
s3transfer==0.1.13
scour==0.36
screen-resolution-extra==0.0.0
SecretStorage==3.1.0
six==1.11.0
Sphinx==1.6.7
sphinx-autodoc-typehints==1.3.0
sphinx-rtd-theme==0.4.2
SQLAlchemy==1.1.11
ssh-import-id==5.7
tblib==1.3.2
typed-ast==1.1.0
ubuntu-drivers-common==0.0.0
ufw==0.35
unattended-upgrades==0.1
urllib3==1.24.1
usb-creator==0.3.3
wcwidth==0.1.7
wurlitzer==1.0.2
xkit==0.0.0
rick@oxygen:~$
