### ISSUE TITLE
Empty profile environment variable raises exception

### ISSUE THREAD

**Issue by JonRoma** [techservicesillinois/awscli-login#35]
It is occasionally useful to temporarily override the profile to log in to an account/role temporarily without opening a new window, using the following command:

```
AWS_PROFILE= aws login  
```

This returns the following error

```
   raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile () could not be found
```

IMHO, an empty profile string should probably be treated the same as when AWS_PROFILE is not defined.

**Comment by ddriddle** [comment]
@JonRoma this bug is not my plugin's fault. It is a problem with Amazon's [awscli](https://github.com/aws/aws-cli) code. After turning off the plugin in `~/.aws/config`, I get the same error message as you do:

```
$ AWS_PROFILE= aws
Traceback (most recent call last):
  File "/Users/ddriddle/src/awscli-login/venv/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/Users/ddriddle/src/awscli-login/venv/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/Users/ddriddle/src/awscli-login/venv/lib/python3.9/site-packages/awscli/clidriver.py", line 69, in main
    rc = driver.main()
  File "/Users/ddriddle/src/awscli-login/venv/lib/python3.9/site-packages/awscli/clidriver.py", line 203, in main
    command_table = self._get_command_table()
  File "/Users/ddriddle/src/awscli-login/venv/lib/python3.9/site-packages/awscli/clidriver.py", line 112, in _get_command_table
    self._command_table = self._build_command_table()
  File "/Users/ddriddle/src/awscli-login/venv/lib/python3.9/site-packages/awscli/clidriver.py", line 129, in _build_command_table
    self.session.emit('building-command-table.main',
  File "/Users/ddriddle/src/awscli-login/venv/lib/python3.9/site-packages/botocore/session.py", line 677, in emit
    return self._events.emit(event_name, **kwargs)
  File "/Users/ddriddle/src/awscli-login/venv/lib/python3.9/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/Users/ddriddle/src/awscli-login/venv/lib/python3.9/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/Users/ddriddle/src/awscli-login/venv/lib/python3.9/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/Users/ddriddle/src/awscli-login/venv/lib/python3.9/site-packages/awscli/customizations/preview.py", line 69, in mark_as_preview
    service_name=original_command.service_model.service_name,
  File "/Users/ddriddle/src/awscli-login/venv/lib/python3.9/site-packages/awscli/clidriver.py", line 328, in service_model
    return self._get_service_model()
  File "/Users/ddriddle/src/awscli-login/venv/lib/python3.9/site-packages/awscli/clidriver.py", line 345, in _get_service_model
    api_version = self.session.get_config_variable('api_versions').get(
  File "/Users/ddriddle/src/awscli-login/venv/lib/python3.9/site-packages/botocore/session.py", line 240, in get_config_variable
    return self.get_component('config_store').get_config_variable(
  File "/Users/ddriddle/src/awscli-login/venv/lib/python3.9/site-packages/botocore/configprovider.py", line 313, in get_config_variable
    return provider.provide()
  File "/Users/ddriddle/src/awscli-login/venv/lib/python3.9/site-packages/botocore/configprovider.py", line 410, in provide
    value = provider.provide()
  File "/Users/ddriddle/src/awscli-login/venv/lib/python3.9/site-packages/botocore/configprovider.py", line 471, in provide
    scoped_config = self._session.get_scoped_config()
  File "/Users/ddriddle/src/awscli-login/venv/lib/python3.9/site-packages/botocore/session.py", line 340, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile () could not be found
```

**Comment by JonRoma** [comment]
Thanks for digging into this. Maybe Amazon will repair this in the CLI v2.
