### ISSUE TITLE
awscli-login failing on windows subsystem for linux (WSL)

### ISSUE THREAD

**Issue by zcarrington** [techservicesillinois/awscli-login#51]
Windows Version 1909, OS build 18363.1256
WSL 2 (backported version)

Here is the output from running aws login and entering password

```
aws login
Password: 

Traceback (most recent call last):
  File "/home/zdc/src/awscli-login/src/awscli_login/saml.py", line 144, in refresh
    jar.load(ignore_discard=True)
  File "/usr/lib/python3.7/http/cookiejar.py", line 1793, in load
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/zdc/.aws-login/cookies/zdc.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zdc/src/awscli-login/src/awscli_login/__main__.py", line 176, in main
    profile.cookies,
  File "/home/zdc/src/awscli-login/src/awscli_login/saml.py", line 147, in refresh
    raise MissingCookieJar(url)
awscli_login.exceptions.MissingCookieJar: Failed to load cookie jar: https://shibboleth.illinois.edu/idp/profile/SAML2/SOAP/ECP

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zdc/src/awscli-login/src/awscli_login/__main__.py", line 124, in wrapper
    f(profile, session)
  File "/home/zdc/src/awscli-login/src/awscli_login/__main__.py", line 181, in main
    profile.cookies, *creds)
  File "/home/zdc/src/awscli-login/src/awscli_login/saml.py", line 118, in authenticate
    soap = saml_login(url, jar, username, password, headers)
  File "/home/zdc/src/awscli-login/src/awscli_login/saml.py", line 92, in saml_login
    r.raise_for_status()
  File "/home/zdc/.local/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Server Error for url: https://shibboleth.illinois.edu/idp/profile/SAML2/SOAP/ECP
```
the plugin POSTed the following:
```XML
<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"
    xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol">
    <S:Body>
        <saml2p:AuthnRequest AssertionConsumerServiceURL="https://signin.aws.amazon.com/saml" ID="_9265E1DCDEA6413A8E688CEB91A0B3A7" IssueInstant="2021-01-09T18:28:13Z" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:PAOS" Version="2.0">
            <saml2:Issuer>urn:amazon:webservices</saml2:Issuer>
        </saml2p:AuthnRequest>
    </S:Body>
</S:Envelope>
```
And the IDP returned:
```XML
<?xml version="1.0" encoding="UTF-8"?>\n<soap11:Envelope xmlns:soap11="http://schemas.xmlsoap.org/soap/envelope/">
    <soap11:Body>
        <soap11:Fault>
            <faultcode>soap11:Client</faultcode>
            <faultstring>An error occurred.</faultstring>
        </soap11:Fault>
    </soap11:Body>
</soap11:Envelope>
```

**Comment by ddriddle** [comment]
@kwessel any idea why the IdP is returning an error? Is the XML that the plugin is sending malformed?

**Comment by zcarrington** [comment]
My time was out of sync in WSL. Synced with ntp.illinois.edu and was able to login with the plugin.
